[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# update dependencies with `cargo update`
dependencies_update = true
# labels for the release PR
pr_labels = ["release"]
# disable git releases (handled by publish workflow)
git_release_enable = false
# disable running `cargo-semver-checks` until after the first release
semver_check = false
